In [117]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine

pd.options.display.max_rows = 999

In [118]:
# The path to our CSV file
file = "population.csv"

# Read our data into pandas
df = pd.read_csv(file)
df.head()

,Data Source,World Development Indicators,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63
0,Last Updated Date,10/28/2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2010.0,2011.0,2012.0,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0,2019.0
3,Aruba,ABW,"Population, total",SP.POP.TOTL,54211.0,55438.0,56225.0,56695.0,57032.0,57360.0,...,101669.0,102046.0,102560.0,103159.0,103774.0,104341.0,104872.0,105366.0,105845.0,NaN
4,Afghanistan,AFG,"Population, total",SP.POP.TOTL,8996973.0,9169410.0,9351441.0,9543205.0,9744781.0,9956320.0,...,29185507.0,30117413.0,31161376.0,32269589.0,33370794.0,34413603.0,35383128.0,36296400.0,37172386.0,NaN

In [119]:
#change data type
#df['1960.0'] = (df['1960.0'] !='n').astype(int)
df.iloc[:,4:]=df.iloc[:,4:].astype(pd.Int64Dtype())
#df.dtypes

#drop rows
df.columns=df.iloc[2]
df.drop(df.index[[0,1,2]], inplace=True)

#drop columns
df.drop(['Indicator Name','Indicator Code'], axis=1, inplace=True)

#drop column with no value ex) 2019
df=df.loc[(df.sum(axis=1) != 0), (df.sum(axis=0) != 0)]

df.rename(columns = {'Country Name':'Country_Name','Country Code':'Country_Code' }, inplace = True) 

df.head(5) #263x60
df.to_csv('population_cleaned.csv', index=False)

In [120]:
file1 = "life.csv"

# Read our data into pandas
df1 = pd.read_csv(file1, skiprows=3)

#drop columns
df1.drop(['Indicator Name','Indicator Code'], axis=1, inplace=True)

#drop raw or column all=0
df1=df1.loc[(df1.sum(axis=1) != 0), (df1.sum(axis=0) != 0)]

df1.rename(columns = {'Country Name':'Country_Name','Country Code':'Country_Code'}, inplace = True)

df1.head(5)  #254x59
df1.to_csv('life_cleaned.csv', index=False)

In [121]:
file2 = "gdp.csv"

# Read our data into pandas
df2 = pd.read_csv(file2, skiprows=3)

#change data type
#df2.iloc[:,4:]=df2.iloc[:,4:].astype(pd.Int64Dtype())
#df.dtypes

#drop rows
#df2.columns=df2.iloc[2]
#df2.drop(df2.index[[0,1,2]], inplace=True)

#drop columns
df2.drop(['Indicator Name','Indicator Code'], axis=1, inplace=True)

#drop raw or column all=0
df2=df2.loc[(df2.sum(axis=1) != 0), (df2.sum(axis=0) != 0)]

df2.rename(columns = {'Country Name':'Country_Name','Country Code':'Country_Code'}, inplace = True)

df2.head(5)  #258x60
df2.to_csv('gdp_cleaned.csv', index=False)

In [122]:
df2.stack()

0    Country_Name                    Aruba
     Country_Code                      ABW
     1986                           6472.5
     1987                           7885.8
     1988                          9764.79
     1989                          11392.5
     1990                          12307.3
     1991                            13496
     1992                          14046.5
     1993                          14936.8
     1994                            16241
     1995                          16439.4
     1996                          16586.1
     1997                          17927.7
     1998                          19078.3
     1999                          19356.2
     2000                          20620.7
     2001                            20669
     2002                          20436.9
     2003                          20833.8
     2004                            22570
     2005                            23300
     2006                          24045.3
     2007                          25835.1
     2008                          27084.7
     2009                          24630.5
     2010                          23512.6
     2011                            24986
     2012                          24713.7
     2013                          25025.1
     2014                          25533.6
     2015                          25796.4
     2016                          25239.6
     2017                          25630.3
1    Country_Name              Afghanistan
     Country_Code                      AFG
     1960                          59.7732
     1961                          59.8609
     1962                           58.458
     1963                          78.7064
     1964                          82.0952
     1965                          101.108
     1966                          137.594
     1967                          160.899
     1968                          129.108
     1969                           129.33
     1970                          156.519
     1971                          159.568
     1972                          135.317
     1973                          143.145
     1974                          173.654
     1975                          186.511
     1976                          197.446
     1977                          224.225
     1978                          247.354
     1979                          275.738
     1980                          272.655
     1981                          264.111
     2002                          179.426
     2003                          190.684
     2004                          211.382
     2005                          242.031
     2006                          263.734
     2007                          359.693
     2008                           364.66
     2009                          438.076
     2010                          543.303
     2011                          591.162
     2012                          641.872
     2013                          637.165
     2014                          613.856
     2015                          578.466
     2016                          547.228
     2017                          556.302
     2018                          520.897
2    Country_Name                   Angola
     Country_Code                      AGO
     1980                          710.982
     1981                          642.384
     1982                          619.961
     1983                          623.441
     1984                          637.715
     1985                          758.238
     1986                           685.27
     1987                          756.262
     1988                          792.303
     1989                          890.554
     1990                          947.704
     1991                          865.693
     1992                          656.362
     1993                          441.201
     1994                          328.673
     1995                          397.179
     1996                          522.644
     1997                          514.295
     1998                          423.594
     1999                          387.784
     2000                          556.836
     2001                          527.334
     2002                          872.494
     2003                          982.961
     2004                          1255.56
     2005                          1902.42
     2006                          2599.57
     2007                             3122
     2008                          4080.94
     2009                          3122.78
     2010                          3587.88
     2011                          4615.47
     2012                           5100.1
     2013                          5254.88
     2014                          5408.41
     2015                          4166.98
     2016                          3506.07
     2017                          4095.81
     2018                          3432.39
3    Country_Name                  Albania
     Country_Code                      ALB
     1984                          639.485
     1985                          639.866
     1986                          693.873
     1987                          674.793
     1988                          652.774
     1989                          697.996
     1990                           617.23
     1991                          336.587
     1992                          200.852
     1993                          367.279
     1994                          586.416
     1995                          750.604
     1996                          1009.98
     1997                          717.381
     1998                           813.79
     1999                          1033.24
     2000                          1126.68
     2001                          1281.66
     2002                          1425.12
     2003                          1846.12
     2004                          2373.58
     2005                          2673.79
     2006                          2972.74
     2007                          3595.04
     2008                          4370.54
     2009                          4114.13
     2010                          4094.36
     2011                          4437.18
     2012                          4247.61
     2013                          4413.08
     2014                          4578.67
     2015                          3952.83
     2016                          4124.11
     2017                          4532.89
     2018                          5253.63
4    Country_Name                  Andorra
     Country_Code                      AND
     1970                          3238.56
     1971                          3498.17
     1972                          4217.17
     1973                          5342.17
     1974                          6319.74
     1975                           7169.1
     1976                          7152.38
     1977                          7751.37
     1978                          9129.71
     1979                          11820.8
     1980                          12377.4
     1981                          10372.2
     1982                          9610.27
     1983                          8022.65
     1984                          7728.91
     1985                          7774.39
     1986                          10361.8
     1987                          12616.2
     1988                          14304.4
     1989                          15166.4
     1990                          18878.5
     1991                          19532.5
     1992                          20547.7
     1993                          16516.5
     1994                          16234.8
     1995                          18461.1
     1996                          19017.2
     1997                          18353.1
     1998                          18894.5
     1999                          19261.7
     2000                          21936.5
     2001                          22228.8
     2002                          24741.5
     2003                          32776.4
     2004                          38503.5
     2005                            41282
     2006                          43747.7
     2007                          48582.2
     2008                          47785.1
     2009                          43338.9
     2010                          39736.4
     2011                          41100.7
     2012                          38392.9
     2013                          40626.8
     2014                          42300.3
     2015                          36039.7
     2016                          37224.1
     2017                          39134.4
     2018                          42029.8
5    Country_Name               Arab World
     Country_Code                      ARB
     1968                          224.086
     1969                          239.304
     1970                           262.12
     1971                          295.181
     1972                          342.669
     1973                          422.034
     1974                           776.21
     1975                          834.706
     1976                          1005.51
     1977                          1121.48
     1978                           1192.1
     1979                          1561.77
     1980                           2050.8
     1981                          2048.58
     1982                          1862.77
     1983                          1697.13
     1984                          1670.37
     1985                             1605
     1986                          1487.92
     1987                          1541.42
     1988                          1473.93
     1989                          1503.39
     1990                          2007.16
     1991                          1926.49
     1992                          2024.72
     1993                          1994.35
     1994                          1986.81
     1995                          2069.99
     1996                          2233.19
     1997                          2316.39
     1998                          2186.75
     1999                          2330.19
     2000                          2603.87
     2001                          2508.21
     2002                          2474.78
     2003                          2734.32
     2004                          3132.33
     2005                          3762.77
     2006                          4356.15
     2007                          4959.92
     2008                          6143.17
     2009                          5182.36
     2010                          5945.68
     2011                          6889.09
     2012                          7503.17
     2013                          7551.28
     2014                          7497.56
     2015                          6459.11
     2016                          6202.89
     2017                          6285.22
     2018                          6626.14
6    Country_Name     United Arab Emirates
     Country_Code                      ARE
     1975                          26847.8
     1976                          30118.1
     1977                          33823.3
     1978                          28456.7
     1979                          33512.7
     1980                          42764.5
     1981                          44987.2
     1982                          40026.2
     1983                          34843.1
     1984                          32309.8
     1985                          29720.9
     1986                            23468
     1987                          23726.2
     1988                          22295.1
     1989                          24028.2
     1990                          27729.5
     1991                          26612.3
     1992                          26420.9
     1993                          25596.7
     1994                          25847.9
     1995                            27222
     1996                            28975
     1997                          29512.7
     1998                          26899.6
     1999                          28470.8
     2000                          33291.4
     2001                          31280.8
     2002                          31567.5
     2003                          33499.1
     2004                          36333.2
     2005                          39365.3
     2006                          41907.4
     2007                          41809.5
     2008                          44498.9
     2009                          32024.2
     2010                          33893.3
     2011                          39194.7
     2012                          40976.5
     2013                          42412.6
     2014                          43751.8
     2015                          38663.4
     2016                          38141.8
     2017                          40325.4
     2018                          43004.9
7    Country_Name                Argentina
     Country_Code                      ARG
     1962                          1155.89
     1963                          850.305
     1964                          1173.24
     1965                          1279.11
     1966                           1272.8
     1967                          1062.54
     1968                          1141.08
     1969                          1329.06
     1970                          1322.59
     1971                          1372.37
     1972                          1408.87
     1973                          2097.02
     1974                          2844.86
     1975                          2027.34
     1976                          1948.22
     1977                          2129.71
     1978                          2146.36
     1979                          2520.92
     1980                          2758.84
     1981                          2776.32
     1982                           2927.9
     1983                          3553.38
     1984                          2659.71
     1985                          2926.13
     1986                          3613.62
     1987                          3562.88
     1988                          3985.19
     1989                          2383.87
     1990                          4333.48
     1991                          5735.36
     1992                          6823.54
     1993                          6969.12
     1994                          7483.14
     1995                          7408.71
     1996                          7721.35
     1997                          8213.13
     1998                          8289.51
     1999                          7774.74
     2000                           7708.1
     2001                          7208.37
     2002                           2593.4
     2003                          3349.81
     2004                          4277.72
     2005                          5109.85
     2006                          5919.01
     2007                          7245.45
     2008                          9020.87
     2009                          8225.14
     2010                            10386
     2011                          12848.9
     2012                          13082.7
     2013                          13080.3
     2014                          12334.8
     2015                          13789.1
     2016                          12790.2
     2017                          14591.9
     2018                          11652.6
8    Country_Name                  Armenia
     Country_Code                      ARM
     1990                          637.855
     1991                          590.121
     1992                          369.633
     1993                          357.203
     1994                          400.515
     1995                          456.375
     1996                          504.059
     1997                          523.283
     1998                          609.172
     1999                          597.433
     2000                          622.742
     2001                          694.423
     2002                          783.241
     2003                          930.127
     2004                          1191.92
     2005                          1643.75
     2006                          2158.14
     2007                          3139.28
     2008                          4010.86
     2009                          2994.34
     2010                          3218.37
     2011                           3525.8
     2012                          3681.86
     2013                          3838.19
     2014                          3986.23
     2015                           3607.3
     2016                          3591.83
     2017                           3914.5
     2018                          4212.07
9    Country_Name           American Samoa
     Country_Code                      ASM
     2002                          8700.07
     2003                          8856.55
     2004                          8578.94
     2005                          8444.98
     2006                          8391.56
     2007                          8909.45
     2008                          9792.67
     2009                          11961.3
     2010                          10271.2
     2011                          10294.3
     2012                          11568.8
     2013                          11505.4
     2014                          11525.2
     2015                          11843.3
     2016                          11714.9
     2017                          11398.8
10   Country_Name      Antigua and Barbuda
     Country_Code                      ATG
     1977                          1246.75
     1978                          1416.59
     1979                          1760.72
     1980                          2124.48
     1981                          2392.26
     1982                           2660.6
     1983                          2947.94
     1984                          3372.49
     1985                          3899.33
     1986                          4703.18
     1987                          5463.24
     1988                          6453.48
     1989                          7076.42
     1990                          7348.21
     1991                          7601.85
     1992                          7744.27
     1993                          8136.17
     1994                          8770.75
     1995                          8406.59
     1996                          9030.98
     1997                          9492.04
     1998                          9940.19
     1999                          10260.6
     2000                          10920.8
     2001                          10370.7
     2002                          10404.4
     2003                            10790
     2004                          11446.6
     2005                          12547.6
     2006                          13989.7
     2007                          15607.1
     2008                          16024.3
     2009                          14113.1
     2010                          13092.1
     2011                          12795.6
     2012                          13399.2
     2013                          13035.1
     2014                          13780.8
     2015                          14526.6
     2016                          15494.3
     2017                          15824.7
     2018                          16864.4
11   Country_Name                Australia
     Country_Code                      AUS
     1960                          1807.79
     1961                          1874.84
     1962                          1851.84
     1963                          1964.15
     1964                          2128.07
     1965                          2277.66
     1966                          2340.44
     1967                          2576.28

In [123]:
#df2.transpose().head(5)

In [124]:
# Create database
db_uri = "sqlite:///db_country.sqlite"
engine = create_engine(db_uri)
engine.execute('CREATE TABLE "Population" ('
               'country_code char(3) NOT NULL,'
               'country_name VARCHAR,'
               'year INT,'
               'value INT,'
               'PRIMARY KEY (country_code));')

for i =  run row
    for j  run column 
        execute. insert 
#engine.execute('INSERT INTO "EX1" '
#               '(id, name) '
#               'VALUES (1,"raw1")')

SyntaxError: invalid syntax (<ipython-input-124-cc40c72540e4>, line 11)

In [125]:
# select *
result = engine.execute('SELECT * FROM '
                        '"Population"')
for _r in result:
   _r

# delete *
#engine.execute('DELETE from "EX1" where id=1;')
#result = engine.execute('SELECT * FROM "EX1"')
#result.fetchall()